/* tslint:disable */
/* eslint-disable */
/**
 * SuppleBox API Document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from '@axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 *
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     *
     * @type {ContactContacts}
     * @memberof Contact
     */
    contacts: ContactContacts;
}
/**
 *
 * @export
 * @interface ContactContacts
 */
export interface ContactContacts {
    /**
     *
     * @type {string}
     * @memberof ContactContacts
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ContactContacts
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof ContactContacts
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof ContactContacts
     */
    content: string;
}
/**
 *
 * @export
 * @interface CreateProduct
 */
export interface CreateProduct {
    /**
     *
     * @type {CreateProductProduct}
     * @memberof CreateProduct
     */
    product: CreateProductProduct;
}
/**
 *
 * @export
 * @interface CreateProductProduct
 */
export interface CreateProductProduct {
    /**
     *
     * @type {string}
     * @memberof CreateProductProduct
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof CreateProductProduct
     */
    image_url: string;
    /**
     *
     * @type {string}
     * @memberof CreateProductProduct
     */
    brand_amazon_name: string;
    /**
     *
     * @type {string}
     * @memberof CreateProductProduct
     */
    url: string;
    /**
     *
     * @type {string}
     * @memberof CreateProductProduct
     */
    asin: string;
    /**
     *
     * @type {number}
     * @memberof CreateProductProduct
     */
    price: number;
}
/**
 *
 * @export
 * @interface CurrentUser
 */
export interface CurrentUser {
    /**
     *
     * @type {CurrentUserUser}
     * @memberof CurrentUser
     */
    user: CurrentUserUser | null;
}
/**
 *
 * @export
 * @interface CurrentUserUser
 */
export interface CurrentUserUser {
    /**
     *
     * @type {number}
     * @memberof CurrentUserUser
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof CurrentUserUser
     */
    name: string;
}
/**
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     *
     * @type {number}
     * @memberof InlineResponse200
     */
    total_pages: number;
    /**
     *
     * @type {Array<Products>}
     * @memberof InlineResponse200
     */
    products: Array<Products>;
}
/**
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     *
     * @type {Array<SearchProducts>}
     * @memberof InlineResponse2001
     */
    products: Array<SearchProducts>;
}
/**
 *
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     *
     * @type {number}
     * @memberof InlineResponse2002
     */
    total_pages: number;
    /**
     *
     * @type {Array<Posts>}
     * @memberof InlineResponse2002
     */
    posts: Array<Posts>;
}
/**
 *
 * @export
 * @interface Login
 */
export interface Login {
    /**
     *
     * @type {LoginUser}
     * @memberof Login
     */
    user?: LoginUser;
}
/**
 *
 * @export
 * @interface LoginUser
 */
export interface LoginUser {
    /**
     *
     * @type {string}
     * @memberof LoginUser
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof LoginUser
     */
    password: string;
}
/**
 *
 * @export
 * @interface NewUser
 */
export interface NewUser {
    /**
     *
     * @type {NewUserUser}
     * @memberof NewUser
     */
    user: NewUserUser;
}
/**
 *
 * @export
 * @interface NewUserUser
 */
export interface NewUserUser {
    /**
     *
     * @type {string}
     * @memberof NewUserUser
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof NewUserUser
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof NewUserUser
     */
    password: string;
    /**
     *
     * @type {string}
     * @memberof NewUserUser
     */
    password_confirmation: string;
}
/**
 *
 * @export
 * @interface Post
 */
export interface Post {
    /**
     *
     * @type {PostPost}
     * @memberof Post
     */
    post: PostPost;
}
/**
 *
 * @export
 * @interface Posts
 */
export interface Posts {
    /**
     *
     * @type {number}
     * @memberof Posts
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof Posts
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof Posts
     */
    content: string;
    /**
     *
     * @type {number}
     * @memberof Posts
     */
    rate: number;
    /**
     *
     * @type {string}
     * @memberof Posts
     */
    picture_url?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof Posts
     */
    is_owner: boolean;
    /**
     *
     * @type {string}
     * @memberof Posts
     */
    edit_path: string;
    /**
     *
     * @type {PostsUser}
     * @memberof Posts
     */
    user: PostsUser;
    /**
     *
     * @type {PostsProduct}
     * @memberof Posts
     */
    product: PostsProduct;
}
/**
 *
 * @export
 * @interface PostsProduct
 */
export interface PostsProduct {
    /**
     *
     * @type {string}
     * @memberof PostsProduct
     */
    image_url: string;
    /**
     *
     * @type {string}
     * @memberof PostsProduct
     */
    path: string;
    /**
     *
     * @type {string}
     * @memberof PostsProduct
     */
    title: string;
}
/**
 *
 * @export
 * @interface PostsUser
 */
export interface PostsUser {
    /**
     *
     * @type {string}
     * @memberof PostsUser
     */
    picture_url: string;
    /**
     *
     * @type {string}
     * @memberof PostsUser
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof PostsUser
     */
    gender?: string | null;
    /**
     *
     * @type {string}
     * @memberof PostsUser
     */
    height?: string | null;
    /**
     *
     * @type {string}
     * @memberof PostsUser
     */
    weight?: string | null;
}
/**
 *
 * @export
 * @interface Product
 */
export interface Product {
    /**
     *
     * @type {ProductProduct}
     * @memberof Product
     */
    product: ProductProduct;
}
/**
 *
 * @export
 * @interface ProductProduct
 */
export interface ProductProduct {
    /**
     *
     * @type {number}
     * @memberof ProductProduct
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof ProductProduct
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof ProductProduct
     */
    image_url: string;
    /**
     *
     * @type {string}
     * @memberof ProductProduct
     */
    url: string;
    /**
     *
     * @type {string}
     * @memberof ProductProduct
     */
    brand_amazon_name: string;
    /**
     *
     * @type {string}
     * @memberof ProductProduct
     */
    price: string;
    /**
     *
     * @type {boolean}
     * @memberof ProductProduct
     */
    is_liked: boolean | null;
}
/**
 *
 * @export
 * @interface Products
 */
export interface Products {
    /**
     *
     * @type {number}
     * @memberof Products
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof Products
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof Products
     */
    image_url: string;
    /**
     *
     * @type {string}
     * @memberof Products
     */
    brand_amazon_name: string;
    /**
     *
     * @type {string}
     * @memberof Products
     */
    product_link: string;
    /**
     *
     * @type {number}
     * @memberof Products
     */
    post_count: number;
    /**
     *
     * @type {number}
     * @memberof Products
     */
    rate: number;
    /**
     *
     * @type {number}
     * @memberof Products
     */
    likes: number;
}
/**
 *
 * @export
 * @interface SearchProducts
 */
export interface SearchProducts {
    /**
     *
     * @type {number}
     * @memberof SearchProducts
     */
    id: number | null;
    /**
     *
     * @type {string}
     * @memberof SearchProducts
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof SearchProducts
     */
    image_url: string;
    /**
     *
     * @type {string}
     * @memberof SearchProducts
     */
    brand_amazon_name: string;
    /**
     *
     * @type {string}
     * @memberof SearchProducts
     */
    product_link: string | null;
    /**
     *
     * @type {string}
     * @memberof SearchProducts
     */
    url: string;
    /**
     *
     * @type {string}
     * @memberof SearchProducts
     */
    asin: string;
    /**
     *
     * @type {number}
     * @memberof SearchProducts
     */
    price: number;
}
/**
 *
 * @export
 * @interface User
 */
export interface User {
    /**
     *
     * @type {UserUser}
     * @memberof User
     */
    user: UserUser;
}
/**
 *
 * @export
 * @interface UserUser
 */
export interface UserUser {
    /**
     *
     * @type {string}
     * @memberof UserUser
     */
    picture_url: string;
    /**
     *
     * @type {string}
     * @memberof UserUser
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof UserUser
     */
    gender: string | null;
    /**
     *
     * @type {string}
     * @memberof UserUser
     */
    height: string | null;
    /**
     *
     * @type {string}
     * @memberof UserUser
     */
    weight: string | null;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Create Products
         * @param {PostPost} post
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPost: async (post: PostPost, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'post' is not null or undefined
            assertParamExists('createPost', 'post', post)
            const localVarPath = `/api/posts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (post !== undefined) {
                localVarFormParams.append('post', new Blob([JSON.stringify(post)], { type: "application/json", }));
            }


            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Create Product
         * @param {CreateProduct} [createProduct] プロテイン登録に必要なパラメーター
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProduct: async (createProduct?: CreateProduct, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createProduct, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Create User
         * @param {NewUser} [newUser]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser: async (newUser?: NewUser, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(newUser, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Delete Post
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePost: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePost', 'id', id)
            const localVarPath = `/api/posts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get Current User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchCurrentUser: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sessions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get Posts
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchPost: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('fetchPost', 'id', id)
            const localVarPath = `/api/posts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get Products
         * @param {number} per per page
         * @param {number} page next page
         * @param {number} [userId]
         * @param {number} [productId]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchPosts: async (per: number, page: number, userId?: number, productId?: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'per' is not null or undefined
            assertParamExists('fetchPosts', 'per', per)
            // verify required parameter 'page' is not null or undefined
            assertParamExists('fetchPosts', 'page', page)
            const localVarPath = `/api/posts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (per !== undefined) {
                localVarQueryParameter['per'] = per;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (productId !== undefined) {
                localVarQueryParameter['product_id'] = productId;
            }



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get Product
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchProduct: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('fetchProduct', 'id', id)
            const localVarPath = `/api/products/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get and Search Products
         * @param {number} per
         * @param {number} page
         * @param {string} [q] For Product Search API
         * @param {number} [userId]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchProducts: async (per: number, page: number, q?: string, userId?: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'per' is not null or undefined
            assertParamExists('fetchProducts', 'per', per)
            // verify required parameter 'page' is not null or undefined
            assertParamExists('fetchProducts', 'page', page)
            const localVarPath = `/api/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (per !== undefined) {
                localVarQueryParameter['per'] = per;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Fetch User
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchUser: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('fetchUser', 'id', id)
            const localVarPath = `/api/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Like Product
         * @param {number} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        likeProduct: async (productId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('likeProduct', 'productId', productId)
            const localVarPath = `/api/products/{product_id}/like`
                .replace(`{${"product_id"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Login
         * @param {Login} [login]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (login?: Login, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sessions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(login, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Login as test user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginAsTestUser: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sessions/test_user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Log out
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sessions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Post Contact
         * @param {Contact} [contact] 問い合わせに必要なパラメータ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postContact: async (contact?: Contact, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/contacts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contact, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Search Products From Amazon
         * @param {string} [keyword] For Amazon Product API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchProductsFromAmazon: async (keyword?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/products/new`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (keyword !== undefined) {
                localVarQueryParameter['keyword'] = keyword;
            }



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Unlike Product
         * @param {number} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlikeProduct: async (productId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('unlikeProduct', 'productId', productId)
            const localVarPath = `/api/products/{product_id}/like`
                .replace(`{${"product_id"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;



            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Update Post
         * @param {number} id
         * @param {PostPost} post
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePost: async (id: number, post: PostPost, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updatePost', 'id', id)
            // verify required parameter 'post' is not null or undefined
            assertParamExists('updatePost', 'post', post)
            const localVarPath = `/api/posts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (post !== undefined) {
                localVarFormParams.append('post', new Blob([JSON.stringify(post)], { type: "application/json", }));
            }


            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Update User
         * @param {number} id
         * @param {EditUserUser} user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser: async (id: number, user: EditUserUser, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateUser', 'id', id)
            // verify required parameter 'user' is not null or undefined
            assertParamExists('updateUser', 'user', user)
            const localVarPath = `/api/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (user !== undefined) {
                localVarFormParams.append('user', new Blob([JSON.stringify(user)], { type: "application/json", }));
            }


            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Create Products
         * @param {PostPost} post
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPost(post: PostPost, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPost(post, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Create Product
         * @param {CreateProduct} [createProduct] プロテイン登録に必要なパラメーター
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProduct(createProduct?: CreateProduct, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProduct(createProduct, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Create User
         * @param {NewUser} [newUser]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUser(newUser?: NewUser, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(newUser, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Delete Post
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePost(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePost(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Get Current User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchCurrentUser(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrentUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchCurrentUser(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Get Posts
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchPost(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Post>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchPost(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Get Products
         * @param {number} per per page
         * @param {number} page next page
         * @param {number} [userId]
         * @param {number} [productId]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchPosts(per: number, page: number, userId?: number, productId?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2002>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchPosts(per, page, userId, productId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Get Product
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchProduct(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Product>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchProduct(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Get and Search Products
         * @param {number} per
         * @param {number} page
         * @param {string} [q] For Product Search API
         * @param {number} [userId]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchProducts(per: number, page: number, q?: string, userId?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchProducts(per, page, q, userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Fetch User
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchUser(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchUser(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Like Product
         * @param {number} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async likeProduct(productId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.likeProduct(productId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Login
         * @param {Login} [login]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(login?: Login, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrentUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(login, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Login as test user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginAsTestUser(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrentUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginAsTestUser(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Log out
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Post Contact
         * @param {Contact} [contact] 問い合わせに必要なパラメータ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postContact(contact?: Contact, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postContact(contact, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Search Products From Amazon
         * @param {string} [keyword] For Amazon Product API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchProductsFromAmazon(keyword?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2001>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchProductsFromAmazon(keyword, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Unlike Product
         * @param {number} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unlikeProduct(productId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unlikeProduct(productId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Update Post
         * @param {number} id
         * @param {PostPost} post
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePost(id: number, post: PostPost, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePost(id, post, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Update User
         * @param {number} id
         * @param {EditUserUser} user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUser(id: number, user: EditUserUser, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUser(id, user, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         *
         * @summary Create Products
         * @param {PostPost} post
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPost(post: PostPost, options?: any): AxiosPromise<object> {
            return localVarFp.createPost(post, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Create Product
         * @param {CreateProduct} [createProduct] プロテイン登録に必要なパラメーター
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProduct(createProduct?: CreateProduct, options?: any): AxiosPromise<object> {
            return localVarFp.createProduct(createProduct, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Create User
         * @param {NewUser} [newUser]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(newUser?: NewUser, options?: any): AxiosPromise<object> {
            return localVarFp.createUser(newUser, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Delete Post
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePost(id: number, options?: any): AxiosPromise<object> {
            return localVarFp.deletePost(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get Current User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchCurrentUser(options?: any): AxiosPromise<CurrentUser> {
            return localVarFp.fetchCurrentUser(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get Posts
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchPost(id: number, options?: any): AxiosPromise<Post> {
            return localVarFp.fetchPost(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get Products
         * @param {number} per per page
         * @param {number} page next page
         * @param {number} [userId]
         * @param {number} [productId]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchPosts(per: number, page: number, userId?: number, productId?: number, options?: any): AxiosPromise<InlineResponse2002> {
            return localVarFp.fetchPosts(per, page, userId, productId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get Product
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchProduct(id: number, options?: any): AxiosPromise<Product> {
            return localVarFp.fetchProduct(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get and Search Products
         * @param {number} per
         * @param {number} page
         * @param {string} [q] For Product Search API
         * @param {number} [userId]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchProducts(per: number, page: number, q?: string, userId?: number, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.fetchProducts(per, page, q, userId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Fetch User
         * @param {number} id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchUser(id: number, options?: any): AxiosPromise<User> {
            return localVarFp.fetchUser(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Like Product
         * @param {number} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        likeProduct(productId: number, options?: any): AxiosPromise<object> {
            return localVarFp.likeProduct(productId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Login
         * @param {Login} [login]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(login?: Login, options?: any): AxiosPromise<CurrentUser> {
            return localVarFp.login(login, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Login as test user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginAsTestUser(options?: any): AxiosPromise<CurrentUser> {
            return localVarFp.loginAsTestUser(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Log out
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: any): AxiosPromise<object> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Post Contact
         * @param {Contact} [contact] 問い合わせに必要なパラメータ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postContact(contact?: Contact, options?: any): AxiosPromise<object> {
            return localVarFp.postContact(contact, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Search Products From Amazon
         * @param {string} [keyword] For Amazon Product API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchProductsFromAmazon(keyword?: string, options?: any): AxiosPromise<InlineResponse2001> {
            return localVarFp.searchProductsFromAmazon(keyword, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Unlike Product
         * @param {number} productId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlikeProduct(productId: number, options?: any): AxiosPromise<object> {
            return localVarFp.unlikeProduct(productId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Update Post
         * @param {number} id
         * @param {PostPost} post
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePost(id: number, post: PostPost, options?: any): AxiosPromise<object> {
            return localVarFp.updatePost(id, post, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Update User
         * @param {number} id
         * @param {EditUserUser} user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser(id: number, user: EditUserUser, options?: any): AxiosPromise<object> {
            return localVarFp.updateUser(id, user, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     *
     * @summary Create Products
     * @param {PostPost} post
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createPost(post: PostPost, options?: any) {
        return DefaultApiFp(this.configuration).createPost(post, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Create Product
     * @param {CreateProduct} [createProduct] プロテイン登録に必要なパラメーター
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createProduct(createProduct?: CreateProduct, options?: any) {
        return DefaultApiFp(this.configuration).createProduct(createProduct, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Create User
     * @param {NewUser} [newUser]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createUser(newUser?: NewUser, options?: any) {
        return DefaultApiFp(this.configuration).createUser(newUser, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Delete Post
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deletePost(id: number, options?: any) {
        return DefaultApiFp(this.configuration).deletePost(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get Current User
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public fetchCurrentUser(options?: any) {
        return DefaultApiFp(this.configuration).fetchCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get Posts
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public fetchPost(id: number, options?: any) {
        return DefaultApiFp(this.configuration).fetchPost(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get Products
     * @param {number} per per page
     * @param {number} page next page
     * @param {number} [userId]
     * @param {number} [productId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public fetchPosts(per: number, page: number, userId?: number, productId?: number, options?: any) {
        return DefaultApiFp(this.configuration).fetchPosts(per, page, userId, productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get Product
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public fetchProduct(id: number, options?: any) {
        return DefaultApiFp(this.configuration).fetchProduct(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get and Search Products
     * @param {number} per
     * @param {number} page
     * @param {string} [q] For Product Search API
     * @param {number} [userId]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public fetchProducts(per: number, page: number, q?: string, userId?: number, options?: any) {
        return DefaultApiFp(this.configuration).fetchProducts(per, page, q, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Fetch User
     * @param {number} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public fetchUser(id: number, options?: any) {
        return DefaultApiFp(this.configuration).fetchUser(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Like Product
     * @param {number} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public likeProduct(productId: number, options?: any) {
        return DefaultApiFp(this.configuration).likeProduct(productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Login
     * @param {Login} [login]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public login(login?: Login, options?: any) {
        return DefaultApiFp(this.configuration).login(login, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Login as test user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public loginAsTestUser(options?: any) {
        return DefaultApiFp(this.configuration).loginAsTestUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Log out
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public logout(options?: any) {
        return DefaultApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Post Contact
     * @param {Contact} [contact] 問い合わせに必要なパラメータ
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postContact(contact?: Contact, options?: any) {
        return DefaultApiFp(this.configuration).postContact(contact, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Search Products From Amazon
     * @param {string} [keyword] For Amazon Product API
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchProductsFromAmazon(keyword?: string, options?: any) {
        return DefaultApiFp(this.configuration).searchProductsFromAmazon(keyword, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Unlike Product
     * @param {number} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public unlikeProduct(productId: number, options?: any) {
        return DefaultApiFp(this.configuration).unlikeProduct(productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Update Post
     * @param {number} id
     * @param {PostPost} post
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updatePost(id: number, post: PostPost, options?: any) {
        return DefaultApiFp(this.configuration).updatePost(id, post, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Update User
     * @param {number} id
     * @param {EditUserUser} user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateUser(id: number, user: EditUserUser, options?: any) {
        return DefaultApiFp(this.configuration).updateUser(id, user, options).then((request) => request(this.axios, this.basePath));
    }
}
