version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./front"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "bundler"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
