require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/update'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'vendor/bundle/**/*'
    - 'public/**/*'
    - 'tmp/**/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/routes.rb'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 125

Naming/VariableName:
  EnforcedStyle: snake_case
  Enabled: true

Style/BlockDelimiters:
  FunctionalMethods:
    - let
    - let!
    - subject

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
