inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/update'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'vendor/bundle/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/routes.rb'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 12
  Exclude:
    - 'app/helpers/application_helper.rb'

Naming/VariableName:
  EnforcedStyle: snake_case
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: false

Style/BlockDelimiters:
  FunctionalMethods:
    - let
    - let!
    - subject
  Exclude:
      - "spec/**/*_spec.rb"

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

# NOTE: 商品情報の属性値の取得はdigで統一したい
Style/SingleArgumentDig:
  Exclude:
    - 'app/models/product.rb'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/EnvironmentVariableAccess:
  AllowReads: true
